import type { NextPage } from "next";
import Head from "next/head";

import { Search } from "@component/Search";

const Home: NextPage = () => {
  return (
    <div className="mx-auto h-full max-h-screen min-h-screen w-full text-white">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col  items-center justify-center bg-slate-900 bg-cover p-4 text-white">
        <Search />
      </main>
    </div>
  );
};

export default Home;
